builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - "386"
    goos:
      - linux
      - windows
    main: .
archives:
  - replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: zip
    files:
      - "README.md"
      - "spec"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc